POST http://localhost:3003/signup
Content-Type: application/json

{
  "status": "A FAZER", 
  "date_schedule": 07-06-2022,  
  "latitude": "0.8",
  "longitude": "0.12",  
  "date_start": "2020/10/10 10:00:00",
  "date_end": "2020/10/10 10:30:00"
} 
