GET http://localhost:3003/test/?name=marca
content-type: application/json

{
    "Marcas": "Ferrari"
}

###
POST http://localhost:3003/products
content-type: application/json

{
    "id": "Imoveis",
    "name": "Apartamento",
    "price": 1200
}

###
GET http://localhost:3003/products

