POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Sergio", 
   "email": "sergio@gmail.com",
   "password": "123456"   
}

###
POST http://localhost:3003/login
Content-Type: application/json

{   
   "email": "sergio@gmail.com",
   "password": "123456"
}

###
POST http://localhost:3003/Post
Content-Type: application/json

{
   "photo": "sergio", 
   "description": "gmail",
   "type": "NORMAL"   
}

 